### ISSUE TITLE
Update to iOS 5

### ISSUE THREAD

**Issue by MikeJaoudi** [orta/WibbleQuest#26]
Yes?

**Comment by orta** [comment]
we can't use any iOS5 specific API's until it's released (its on NDA)
do you mean switching to ARC? That's possible, kinda.

When I looked into ARC, I came up against problems with KIF ( The testing / walkthrough framework )
which means either porting _that_ to ARC first ( 0.0 ) or having a nice think about it.

**Comment by MikeJaoudi** [comment]
Shall we upgrade to ARC since we can upgrade it w/o upgrading KIF.

Are there any other iOS 5 features we wanna add?

**Comment by orta** [comment]
This is definitely something to look at now, other things worth looking aft are saving state across iCloud I think, you've got a ticket open about saving and I'll have a think about this too

**Comment by orta** [comment]
consider it done.
