### ISSUE TITLE
allow setting a css file through your game object

### ISSUE THREAD

**Issue by orta** [orta/WibbleQuest#31]
so that different Games in the same code base can have different styles.

**Comment by MikeJaoudi** [comment]
we would have to restructure things because the web view is the first thing that loads. we could also have an external file that specifies which css file to load

**Comment by orta** [comment]
This is true, however, we can use javascript to create a new link tag
to a stylesheet which should bring in the additional style.

http://rickardnilsson.net/post/2008/08/02/Applying-stylesheets-dynamically-with-jQuery.aspx

It's a one liner from the web view perspective, the API for it however
needs a bit of thinking about. Should it just go on the WibbleQuest
object? ( [wq addStyleSheet:@"blah.css"] ) or should it have its own
class?

On Fri, Sep 16, 2011 at 1:22 AM, MJaoudi
reply@reply.github.com
wrote:

**Comment by ghost** [comment]
I think it should go with the WibbleQuest object. It already does all the output. A stylesheet would be be output in a way too. Also making a new object might be harder.

I would suggest forking it and seeing which way is better.

**Comment by orta** [comment]
I agree Artmig.

**Comment by orta** [comment]
doned
